{
    "name": "Amb purchase",
    "summary": "Amb purchase",
    "description": "Amb purchase",
    "version": "17.0.1.0.0",
    "author": "Aktiv software / Groupe OCI",
    "website": "http://www.aktivsoftware.com / https://www.oci.fr",
    "category": "purchase",
    "license": "LGPL-3",
    "depends": [
        "base",
        "purchase",
        "l10n_fr",
        "account",
        "purchase_stock",
        "amb_studio",
        "amb_subscription",
        "fields_module",
    ],
    "data": [
        "data/report_paperformat.xml",
        "report/custom_external_layout.xml",
        "report/custom_report_purchaseorder.xml",
        "report/custom_report_purchasequotation.xml",
        "views/purchase_views.xml",
    ],
    "application": True,
    "auto_install": False,
    "installable": True,
}
